### PR TITLE
If Blob is not present, use Buffer

### PR DESCRIPTION
**Pull request by glasserc**
Attempt to address #468. There may be other NodeJS problems, but let's take them one at a time.

### CODE REVIEW

**Comment by ncloudioj** [comment]
Yes, it works now (with the two extra shims for "atob" and "FormData")!

Thank y'all!

**Comment by glasserc** [comment]
I guess we can merge this since it makes things better and it's a pretty easy fix. @ncloudioj suggests that we should shim `atob`, `FormData`, and `fetch` (using `node-fetch`). If this doesn't get merged, I'll try to add those to this PR as I figure out how.

**Comment by leplatrem** [comment]
I don't know if it is the responsibility of a library to shim everything from browser.

**Comment by leplatrem** [comment]
Let's merge this and discuss about additional shims elsewhere!

**Pull request merged**
