### PR TITLE
Fix Travis test setup.

### PR DESCRIPTION
**Pull request by n1k0**
Tests were not running on Travis. This should fix it.

### CODE REVIEW

**Comment by n1k0** [comment]
Interesting, we have a single failure:



Failing test code:



Do we know about recent changes in Kinto master which could cause this failure? @Natim @leplatrem @glasserc @gabisurita

**Comment by Natim** [comment]
```json
$ echo '{}' | http POST https://kinto.dev.mozaws.net/v1/buckets --auth test:
HTTP/1.1 201 Created
Access-Control-Expose-Headers: Retry-After, Alert, Backoff, Content-Length
Connection: keep-alive
Content-Length: 159
Content-Type: application/json
Date: Tue, 07 Mar 2017 07:48:10 GMT
ETag: "1488872890652"
Last-Modified: Tue, 07 Mar 2017 07:48:10 GMT
Server: nginx
X-Content-Type-Options: nosniff

{
    "data": {
        "id": "symcJS-p", 
        "last_modified": 1488872890652
    }, 
    "permissions": {
        "write": [
            "basicauth:df93ca0ecaeaa3126595f6785b39c408be2539173c991a7b2e3181a9826a69bc"
        ]
    }
}

rhubscher@rhubscher-ThinkPad-T460s:~$ echo '{"data": {"synced": "Yo"}}' | http POST https://kinto.dev.mozaws.net/v1/buckets/symcJS-p/collections --auth natim:
HTTP/1.1 201 Created
Access-Control-Expose-Headers: Retry-After, Alert, Backoff, Content-Length
Connection: keep-alive
Content-Length: 173
Content-Type: application/json
Date: Tue, 07 Mar 2017 07:48:35 GMT
ETag: "1488872915785"
Last-Modified: Tue, 07 Mar 2017 07:48:35 GMT
Server: nginx
X-Content-Type-Options: nosniff

{
    "data": {
        "id": "wIhJ0Oo-", 
        "last_modified": 1488872915785, 
        "synced": "Yo"
    }, 
    "permissions": {
        "write": [
            "basicauth:df93ca0ecaeaa3126595f6785b39c408be2539173c991a7b2e3181a9826a69bc"
        ]
    }
}

rhubscher@rhubscher-ThinkPad-T460s:~$ http GET https://kinto.dev.mozaws.net/v1/buckets/symcJS-p/collections/wIhJ0Oo- --auth natim:
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Retry-After, Cache-Control, Pragma, Expires, Last-Modified, Alert, Backoff, ETag, Content-Length
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Length: 173
Content-Type: application/json
Date: Tue, 07 Mar 2017 07:48:51 GMT
ETag: "1488872915785"
Last-Modified: Tue, 07 Mar 2017 07:48:35 GMT
Server: nginx
X-Content-Type-Options: nosniff

{
    "data": {
        "id": "wIhJ0Oo-", 
        "last_modified": 1488872915785, 
        "synced": "Yo"
    }, 
    "permissions": {
        "write": [
            "basicauth:df93ca0ecaeaa3126595f6785b39c408be2539173c991a7b2e3181a9826a69bc"
        ]
    }
}
```

**Comment by leplatrem** [comment]
The `setData()` is doing a `PUT` request

**Comment by Natim** [comment]
Yes I tried different combination.

**Comment by leplatrem** [comment]
```
echo '{"data": {"signed": true}}' | http PUT :8888/v1/buckets/default/collections/a --auth a:a
HTTP/1.1 201 Created
Access-Control-Expose-Headers: Alert, Backoff, Retry-After, Content-Length
Content-Length: 166
Content-Type: application/json
Date: Tue, 07 Mar 2017 09:04:24 GMT
Etag: "1488877464271"
Last-Modified: Tue, 07 Mar 2017 09:04:24 GMT
Server: waitress
X-Content-Type-Options: nosniff

{
    "data": {
        "id": "a", 
        "last_modified": 1488877464271, 
        "signed": true
    }, 
    "permissions": {
        "write": [
            "basicauth:0698509a4003c5a0f9bc4e8e23baaeb5379eb61546ae4d1fd7cd179a8786da89"
        ]
    }
}
```

```
http GET :8888/v1/buckets/default/collections/a --auth a:a 
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Retry-After, Backoff, Content-Length, Pragma, Alert, ETag, Expires, Last-Modified, Cache-Control
Cache-Control: no-cache, no-store
Content-Length: 152
Content-Type: application/json
Date: Tue, 07 Mar 2017 09:04:37 GMT
Etag: "1488877477975"
Last-Modified: Tue, 07 Mar 2017 09:04:37 GMT
Server: waitress
X-Content-Type-Options: nosniff

{
    "data": {
        "id": "a", 
        "last_modified": 1488877477975
    }, 
    "permissions": {
        "write": [
            "basicauth:0698509a4003c5a0f9bc4e8e23baaeb5379eb61546ae4d1fd7cd179a8786da89"
        ]
    }
}
```

**Comment by leplatrem** [comment]
Requires https://github.com/Kinto/kinto/pull/1137 for tests to pass

**Pull request merged**
